spring.application.name=GP

# ============================================================
# DATABASE — Aiven MySQL (production)
# ============================================================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=false

# ============================================================
# STRIPE — попълнете с реалните си ключове от Stripe Dashboard
# ============================================================

stripe.secret-key=${SK_STRIP}
stripe.webhook-secret=${WH_STRIP}

# ============================================================
# APP — Render URL
# ============================================================
app.base-url=https://gdd-program.onrender.com

# ============================================================
# ACTUATOR
# ============================================================
management.endpoints.web.exposure.include=*
management.endpoint.prometheus.access=unrestricted
management.metrics.tags.application=gdd-program


# ============================================================
# SERVER — Render използва PORT environment variable
# ============================================================
server.port=${PORT:8080}
